### ISSUE TITLE
Beautiful prompts

### ISSUE THREAD

**Issue by dbalabka** [nickto/gpt-cli#1]
I belive this UI CLI toolkit can help to improve UX:
https://python-prompt-toolkit.readthedocs.io/en/master/index.html

**Comment by nickto** [comment]
Implemented in https://gitlab.com/nickto/gpt-cli/-/merge_requests/1 

It allows now:
- Writing a multiline input using Meta + Enter (Esc + Enter).
- Pasting a multiline input.
- Navigating an input using left\right arrows.
- Accessing an input history using up/down arrows.

**Comment by dbalabka** [comment]
Amazing 🤩 thanks. Can’t wait to try
